FROM php:7.4-apache  
#COPY . /var/www/php
COPY src/ /var/www/html
EXPOSE 80


# BELOW TODO
# sudo docker build . -t basic-php-app:v1
# sudo docker container run -d -p 80:80 basic-php-app:v1
# curl localhost:80
