def PrintStageName() {
  echo "-----------------${env.STAGE_NAME}-----------------"
}


pipeline {

  agent { label 'linux-agents' }


  triggers {  //before the stages, so no need to configure it seperately in diff section on jenkins gui
    pollSCM 'H/10 * * * *'
  }


  environment {

    DOCKER_REGISTRY_URL = "https://registry.hub.docker.com"

    DOCKERHUB_USERNAME = "fedora800"
    APP_NAME = "june-proj-app"
    DOCKER_IMAGE_NAME = "${DOCKERHUB_USERNAME}" + "/" + "${APP_NAME}"
    DOCKER_REGISTRY_NAME = "dockerhub"
    DOCKER_IMAGE_TAG_1 = "${BUILD_NUMBER}"
    DOCKER_IMAGE_TAG_2 = "latest"

    REGISTRY_AUTH = credentials("docker-registry")

  }

  stages {

    stage("Stage-Print-Build-Number"){
      steps{
        PrintStageName()
        echo "BUILD_NUMBER = ${env.BUILD_NUMBER}"
      }
    }


    stage('Stage-Get-git-Repo')  {
      steps {
        PrintStageName()
        script {
          try{
            // Pull code from a GitHub repository
            git branch: 'main', url: 'https://github.com/fedora800/scratch_project.git'
          }
          catch (err) {
            echo err
          }
        }
      }
    }


    stage("Connect to Docker Registry and authenticate with credentials - Using Jenkins function") {
      steps {
        PrintStageName()
        script {
          docker.withRegistry($DOCKER_REGISTRY_URL, 'docker-hub-credentials') {

          }
        }
    }

    } // end-stages


}

