def PrintStageName() {
  echo "-----------------${env.STAGE_NAME}-----------------"
}


pipeline {

  agent { label 'linux-agents' }


  triggers {  
    pollSCM '*/2 * * * *'
  }


  environment {

    DOCKER_REGISTRY_URL = "https://registry.hub.docker.com"
    DOCKERHUB_USERNAME = "fedora800"
    DOCKERHUB_PASSWORD_TOKEN = "dckr_pat_bIVSJy3byydo43Wnzb6WxrV17Ag"
    DOCKER_IMAGE_TAG_1 = "${env.BUILD_NUMBER}"
    DOCKER_IMAGE_TAG_2 = "latest"

    GITHUB_REPO_URL = "https://github.com/fedora800/scratch_project.git"
    GITHUB_REPO_BRANCH = "main"
    GIT_HUB_CREDENTIALS = "j_github_credentials"

    APP_NAME = "basic-nginx-docker-app"

  }

  stages {

    stage("Stage-Print-Build-Number")  {
      steps{
        PrintStageName()
        echo "BUILD_NUMBER = ${env.BUILD_NUMBER}"
      }
    }


    stage('Stage-Get-git-Repo -- using withCredentials function')  {
      steps {
        PrintStageName()
        withCredentials([gitUsernamePassword(credentialsId: 'j_github_credentials', gitToolName: 'git-tool')]) {
          sh 'git fetch --all'
        }
      }
    }


    stage("Connect to Docker Registry and authenticate with credentials - Using Shell commands") {
      steps {
        PrintStageName()
        script {
          sh "hostnamectl"
          sh "echo $DOCKERHUB_PASSWORD_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin"
        }
      }
    }


    stage("Build Docker Image - Using Shell commands") {
      steps {
        PrintStageName()
        script {
          sh "docker build --tag $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_1 --tag $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_2 ."
        }
      }
    }


    stage("Push Docker Image - Using Shell commands") {
      steps {
        PrintStageName()
        script {
          sh "docker push $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_1"
          sh "docker push $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_2"
        }
      }
    }

    stage("Logout from the Docker Registry - Using Shell commands") {
      steps {
        PrintStageName()
        script {
          sh "docker logout"
        }
      }
    }


    stage("Clean up local docker images - Using Shell commands") {
      steps {
        PrintStageName()
        script {
          sh "docker image rm $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_1"
          sh "docker image rm $DOCKERHUB_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG_2"
        }
      }
    }


  } // end-stages


}

