def PrintStageName() {
  echo "-----------------${env.STAGE_NAME}-----------------"
}

pipeline {

   agent { label 'linux-agents' }

   stages {

      stage("Stage-Print-Build-Number"){
        steps{
          PrintStageName()
          echo "BUILD_NUMBER = ${env.BUILD_NUMBER}"
        }
      }

        stage('Stage-Get-git-Repo')  {
               
            steps {
              PrintStageName()
                script {
                     try{
                           // Get some code from a GitHub repository
                           git url: 'https://github.com/fedora800/projCert.git', branch: 'main' 
                      
                     }
                     catch (err){
                           echo err
                     }
                }
             }
        }

        // stage-monitor
        stage("STAGE-MONITOR") {
            steps { 
              PrintStageName()
              echo "Monitor"  
            }
        }

    } // end-stages


}

