apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox
spec:
  containers:
  - name: ctr-busybox
    image: busybox
    command:
      - sleep
      - "3600"
    # command: ["/bin/sh", "-c", "while true; do date >> /tmp/looptest.log ; ls -l /tmp/looptest.log  >> /tmp/looptest.log; sleep 5; done"]
    # to access -> kubectl exec -it pod-busybox -- sh
