apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-manual-1gb
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
