apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rlb-for-myapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer
subjects:
  - kind: ServiceAccount
    name: sa-for-app1
    namespace: kube-system
