apiVersion: v1
kind: Secret
metadata:
  name: sct-postgres-
  namespace: ns-myname                                        # optional
type: Opaque
data:
  password: cG9zdGdyZXM=                                      # echo -n "postgres" | base64
