# https://kodekloud.com/blog/how-to-build-a-docker-image/
ARG PYTHON_VERSION=3.11-slim
FROM python:${PYTHON_VERSION}
WORKDIR /app
COPY requirements.txt /app
#COPY app.py /app
COPY . /app                 # copy all code
RUN pip install -r requirements.txt
ENV FLASK_APP=app.py
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
# sudo docker build . -t basic-flask-app:latest
# sudo docker container run -d -p 5000:80 basic-flask-app:latest             # publish container port 5000 to machine port 80
# curl localhost:80
